version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    schedule:
      interval: "weekly"
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@typescript-*"
      typedoc:
        patterns:
          - "typedoc"
          - "typedoc-*"
          - "@typedoc/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      rollup:
        patterns:
          - "rollup"
          - "rollup-*"
          - "@rollup/*"
      oojs:
        patterns:
          - "oojs*"
          - "@types/oojs*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

