import DeputyCasePage from '../wiki/DeputyCasePage';

/**
 * Represents a ContributionSurveySection. Contains a list of {@link ContributionSurveyRow}s
 * that make up a section generated by the contribution survey.
 */
export default class ContributionSurveySection {

	/**
	 * The case page of this section
	 */
	casePage: DeputyCasePage;
	/**
	 * The name of this section (based on the heading).
	 */
	name: string;
	/**
	 * Whether this section has been closed (wrapped in collapse templates)
	 */
	closed: boolean;
	/**
	 * Closing comments for this section
	 */
	closingComments: string;

	/**
	 * Whether the section was already closed
	 */
	readonly originallyClosed: boolean;
	/**
	 * The original wikitext of this section
	 */
	readonly originalWikitext: string;

	/**
	 * @param casePage The case page of this section
	 * @param name The name of this section (based on the heading)
	 * @param closed Whether this section has been closed (wrapped in collapse templates)
	 * @param closingComments Closing comments for this section
	 * @param wikitext The original wikitext of this section
	 */
	constructor(
		casePage: DeputyCasePage,
		name: string,
		closed: boolean,
		closingComments: string,
		wikitext: string
	) {
		this.casePage = casePage;
		this.name = name;
		this.closed = closed;
		this.closingComments = closingComments;

		this.originalWikitext = wikitext;
		this.originallyClosed = closed;
	}

}
