name: CI/CD

on:
  push:
  pull_request:

jobs:
  tests:
    name: Perform tests
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[failing]') }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        product: [ 'chrome', 'firefox' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Firefox
        if: matrix.product == 'firefox'
        uses: browser-actions/setup-firefox@latest

      - name: Install geckodriver
        if: matrix.product == 'firefox'
        uses: browser-actions/setup-geckodriver@latest

      - name: Install chromedriver
        if: matrix.product == 'chrome'
        uses: nanasess/setup-chromedriver@v1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          BROWSER: ${{ matrix.product }}

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-artifacts
          path: tests/artifacts/*

      - name: Upload transpiled code
        uses: actions/upload-artifact@v3
        with:
          name: builds
          path: build/*.js

      - name: Upload sourcemaps
        uses: actions/upload-artifact@v3
        with:
          name: sourcemaps
          path: build/*.js.map
