name: CI/CD

on:
  push:
    branches:
      - 'main'
    tags:
      - v*
  pull_request:

jobs:
  audit:
    name: Perform NPM audits
    runs-on: ubuntu-latest
    env:
      NODE_ENV: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Perform audit (backend)
        uses: oke-py/npm-audit-action@v1.8.3
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Perform tests
    runs-on: ubuntu-latest
    needs: audit
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        product: ['chrome', 'firefox']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
        env:
          PUPPETEER_PRODUCT: ${{ matrix.product }}
